FROM node:14 AS build

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm ci
COPY . .
RUN npm run build:staging

# production environment
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
