FROM node:alpine AS build

WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build:production

# production environment
FROM nginx:stable
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 3000
