const NAMES_DESCRIPTION = [
  {
    key: 'label',
    displayLabel: 'Label',
    componentType: 'Input',
    isEditable: true,
    isShown: true,
    canBeNull: true,
  },
  {
    key: 'acronym',
    displayLabel: 'Acronym',
    componentType: 'Input',
    isEditable: true,
    isShown: true,
    canBeNull: true,
  },
  {
    key: 'created_at',
    displayLabel: 'Created_at',
    componentType: 'InputDate',
    isEditable: false,
    isShown: false,
    canBeNull: false,
  },
  {
    key: 'created_by',
    displayLabel: 'created_by',
    componentType: 'Input',
    isEditable: false,
    isShown: false,
    canBeNull: false,
  },
  {
    key: 'modified_at',
    displayLabel: 'modified_at',
    componentType: 'InputDate',
    isEditable: false,
    isShown: false,
    canBeNull: true,
  },
  {
    key: 'modified_by',
    displayLabel: 'modified_by',
    componentType: 'Input',
    isEditable: false,
    isShown: false,
    canBeNull: true,
  },
  {
    key: 'start_date',
    displayLabel: 'Date de début',
    componentType: 'InputDate',
    isEditable: false,
    isShown: true,
    canBeNull: false,
  },
  {
    key: 'end_date',
    displayLabel: 'Date de fin',
    componentType: 'InputDate',
    isEditable: false,
    isShown: true,
    canBeNull: true,
  },
  {
    key: 'status',
    displayLabel: 'Statut',
    componentType: 'Status',
    isEditable: true,
    isShown: true,
    canBeNull: false,
  },
];

export default NAMES_DESCRIPTION;
